mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')), 
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
        path('', views.IndexView.as_view(), name='index'),
        path('<int:pk>/', views.DetailView.as_view(), name='detail'),
        path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
        path('<int:question_id>/vote/', views.vote, name='vote'),
        path('comments/', views.comments, name = 'comments'),
        path('comments/list/', views.commentslist, name = 'List of Comments')
    ]

polls/models.py
import datetime


from django.db import models
from django.utils import timezone

class Question(models.Model):
      question_text = models.CharField(max_length=200)
      pub_date = models.DateTimeField('date published')
      def __str__(self):
                  return self.question_text
      def was_published_recently(self):
          now = timezone.now()
          return now - datetime.timedelta(days=1) <= self.pub_date <= now
      was_published_recently.admin_order_field = 'pub_date'
      was_published_recently.boolean = True
      was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
                return self.choice_text

class Comment(models.Model):
    name_field = models.CharField(max_length = 50, default = "ANON")
    comment_text = models.TextField()
    def __str__(self):
        return self.comment_text
# Create your models here.

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from django.utils import timezone
from .models import Choice, Question, Comment

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
                Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

def comments(request):
    if request.method == 'POST':
        name_field = request.POST.get('name_field')
        comment_text = request.POST.get('comment_text')
        commentObject = Comment(name_field = name_field, comment_text = comment_text)
        commentObject.save()
        comments = Comment.objects.all()
    return render(request, 'polls/comment.html',{'comment': comments})

def commentslist(request):
    commentslist = Comment.objects.all()
    return render(request, 'polls/list.html', {'commentslist': commentslist})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args= (question.id,)))

polls/templates/polls/comments.html
<html>
	<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
			</head>

<div class="text-center">


<h1> Comments page <small> Make your comments here.</small></h1>
</div>

<form action="{% url 'polls:comments' %}" method="post">
<p class="text-center">

{% csrf_token %}
	<g class="text-uppercase">
		<u> Name: </u> <br>
					</g>
	<input type="text" name="name_field"><br>
	<a class="text-uppercase">
		<u> Comment: </u> <br>
	</a>
	<textarea class = "form-control" rows="5" cols = "2" name = "comment_text"><textarea>

	<input type="submit" class="text-info" value="Make comment">
</form>

<footer> Rachel Benton <cite title="Name"></cite></footer>
<footer> rmb6xz <cite title="ComputingID"></cite></footer>


<html>

polls/templates/polls/detail.html
<html>
	<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
			</head>

<div class="text-center">
<h1>{{ question.question_text }}</h1>
</div>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_tex }}</label<br>
{% endfor %}
<button type="submit" value="Vote">Vote</button>
</form>

<footer> Rachel Benton <cite title="Name"></cite></footer>
<footer> rmb6xz <cite title="ComputingID"></cite></footer>


<html>

polls/templates/polls/index.html
<html>
	<head>
<link rel="stylesheet" href"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
					</head>

{% load static %}



<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ queston.question_text }}</a></li>
    {% endfor %}
    </ul>
 {% else %}
    <p> No polls are available. </p>
 {% endif %}
 <footer> Rachel Benton <cite title="Name"></cite></footer>
 <footer> rmb6xz <cite title="ComputingID"></cite></footer>

 <html>

polls/templates/polls/list.html
<html>
		<head>

<link rel="styleshee" href="ttps://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/j/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
				</head>

<div class= "text-center">
<h1> List of Comments! </h1>
</div>

<ul>

{% for comment in commentslist %}
<li> {{comment.name_field }} -- {{ comment.comment_text }} </li>
    {% endfor %}
</ul>

<footer> Rachel Benton <cite title="Name"></cite></footer>
<footer> rmb6xz <cite title="ComputingID"></cite></footer>

<html>

polls/templates/polls/results.html
<html>
		<head>
<link rel="stylesheet" href="htts://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4GsO3+Hhxv8T/5PaXtkKtu6ug5TOeNV6gBiFeWPGF9MuhOf23Q9Ifjh" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
				</head>
<div class = "text-center">
<h1>{{ question.question_text }}</h1>
</div>



<ul>
{% for choice in question.choice_set.all %}
<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
{% endfor %}
</ul>

<a href="{%url 'polls:detail' question.id %}">Vote again?</a>
<footer> Rachel Benton <cite title="Name"></cite></footer>
<footer> rmb6xz <cite title="ComputingID"></cite></footer>


<html>